//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week6CodeChallenge_LKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Week6Contacts
    {
        public int CustomerID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Nullable<int> PhoneNumber { get; set; }
        public string CompanyName { get; set; }
        public string ProjectDescription { get; set; }
        public string Comment { get; set; }
    }
}
